In [1]:
#import libraries
import pandas as pd
import numpy as np
import collections

In [2]:
#load dataset
dataset = pd.read_excel("Experiment_1.xlsx")
dataset

,Time Stamp,Time (s),43: Door_TC_1 (°C),54: TC_Smoke (°C),154: TC_Tree_Tr1_060 (°C),163: TC_Tree_Tr1_110 (°C),155: TC_Tree_Tr1_160 (°C),164: TC_Tree_Tr1_210 (°C),156: TC_Tree_Tr1_260 (°C),157: TC_Tree_Tr2_060 (°C),...,167: TC_Tree_Tr5_110 (°C),161: TC_Tree_Tr5_160 (°C),168: TC_Tree_Tr5_210 (°C),162: TC_Tree_Tr5_260 (°C),175: TC_Tree_Tr6_060 (°C),182: TC_Tree_Tr6_110 (°C),176: TC_Tree_Tr6_160 (°C),183: TC_Tree_Tr6_210 (°C),177: TC_Tree_Tr6_260 (°C),187: CO_room (%)
0,2017-02-16 10:11:16,-1098.0,6.744366,8.613041,11.223265,11.993290,12.528495,13.859805,16.129905,10.114287,...,11.715737,12.821863,14.512621,15.980734,10.637421,11.486481,12.803136,14.597771,16.100139,0.069557
1,2017-02-16 10:11:17,-1097.0,6.742377,8.614577,11.227882,12.010446,12.532022,13.871086,16.136226,10.116304,...,11.717507,12.820058,14.515644,15.991423,10.647445,11.498340,12.816788,14.613598,16.106280,0.069368
2,2017-02-16 10:11:18,-1096.0,6.733968,8.612079,11.240460,12.034836,12.536730,13.877260,16.144257,10.113530,...,11.719682,12.822691,14.521757,15.999166,10.637209,11.489658,12.801362,14.607518,16.103539,0.068637
3,2017-02-16 10:11:19,-1095.0,6.734870,8.603408,11.239512,12.029839,12.528744,13.873360,16.134282,10.104086,...,11.714729,12.815942,14.520780,15.988569,10.631385,11.490874,12.801581,14.600377,16.100479,0.069021
4,2017-02-16 10:11:20,-1094.0,6.754570,8.608649,11.239272,12.022808,12.524825,13.865656,16.131178,10.104755,...,11.708731,12.808195,14.520311,15.983372,10.635115,11.492837,12.799479,14.606339,16.100059,0.070498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11757,2017-02-16 13:27:13,10659.0,16.184975,7.438120,16.002027,26.998183,31.145460,28.729846,96.087471,15.558452,...,24.097058,31.692171,38.198730,46.310816,20.769895,23.977180,33.330193,37.946091,35.455440,0.085909
11758,2017-02-16 13:27:14,10660.0,16.171954,7.435278,15.962836,27.028555,31.133574,28.725435,97.108398,15.621120,...,24.080096,31.653633,38.144099,46.388668,20.743634,24.019891,33.357163,37.934598,35.577285,0.087357
11759,2017-02-16 13:27:15,10661.0,16.402681,7.450907,15.935725,26.967670,31.101856,28.711491,97.787657,15.667918,...,24.097512,31.630430,38.099531,46.468133,20.714681,24.047620,33.382168,37.953703,35.654298,0.088566
11760,2017-02-16 13:27:16,10662.0,16.729246,7.450153,15.961972,26.921254,31.097957,28.755888,97.583848,15.713728,...,24.167667,31.642482,38.136747,46.537941,20.743513,24.048995,33.408958,38.001494,35.717997,0.089609
11761,2017-02-16 13:27:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#pick only the useful columns
df=dataset[['54: TC_Smoke (°C)', '154: TC_Tree_Tr1_060 (°C)', '156: TC_Tree_Tr1_260 (°C)',
                  '157: TC_Tree_Tr2_060 (°C)', '159: TC_Tree_Tr2_260 (°C)', '169: TC_Tree_Tr3_060 (°C)', 
                  '171: TC_Tree_Tr3_260 (°C)', '172: TC_Tree_Tr4_060 (°C)', '174: TC_Tree_Tr4_260 (°C)',
                  '160: TC_Tree_Tr5_060 (°C)', '162: TC_Tree_Tr5_260 (°C)', '175: TC_Tree_Tr6_060 (°C)',
                  '177: TC_Tree_Tr6_260 (°C)', '187: CO_room (%)']]

#convert CO_room in percentage to ppm
df.loc[:,"187: CO_room (ppm)"] = df.loc[:,"187: CO_room (%)"].apply(lambda x : x*10000)

#remove CO_room in percentage from the dataframe
cols = list(df.columns)
cols.remove("187: CO_room (%)")
del df['187: CO_room (%)']

df

/Users/adenreleishola/opt/anaconda3/envs/tfs/lib/python3.7/site-packages/pandas/core/indexing.py:1667: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value

,54: TC_Smoke (°C),154: TC_Tree_Tr1_060 (°C),156: TC_Tree_Tr1_260 (°C),157: TC_Tree_Tr2_060 (°C),159: TC_Tree_Tr2_260 (°C),169: TC_Tree_Tr3_060 (°C),171: TC_Tree_Tr3_260 (°C),172: TC_Tree_Tr4_060 (°C),174: TC_Tree_Tr4_260 (°C),160: TC_Tree_Tr5_060 (°C),162: TC_Tree_Tr5_260 (°C),175: TC_Tree_Tr6_060 (°C),177: TC_Tree_Tr6_260 (°C),187: CO_room (ppm)
0,8.613041,11.223265,16.129905,10.114287,15.644292,9.149008,15.963158,11.374617,16.100735,10.229838,15.980734,10.637421,16.100139,695.565623
1,8.614577,11.227882,16.136226,10.116304,15.652686,9.169949,15.969934,11.376564,16.108469,10.240968,15.991423,10.647445,16.106280,693.682888
2,8.612079,11.240460,16.144257,10.113530,15.654990,9.162686,15.966794,11.370615,16.110418,10.242827,15.999166,10.637209,16.103539,686.368593
3,8.603408,11.239512,16.134282,10.104086,15.644093,9.155089,15.959317,11.369386,16.107869,10.235402,15.988569,10.631385,16.100479,690.206866
4,8.608649,11.239272,16.131178,10.104755,15.641486,9.162542,15.966950,11.377520,16.118785,10.238772,15.983372,10.635115,16.100059,704.980179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11757,7.438120,16.002027,96.087471,15.558452,78.265124,20.752476,59.189023,17.136325,NaN,20.346706,46.310816,20.769895,35.455440,859.086899
11758,7.435278,15.962836,97.108398,15.621120,78.252681,20.744750,58.927754,17.131258,NaN,20.311691,46.388668,20.743634,35.577285,873.570764
11759,7.450907,15.935725,97.787657,15.667918,78.245026,20.714536,58.661037,17.139667,NaN,20.260156,46.468133,20.714681,35.654298,885.664478
11760,7.450153,15.961972,97.583848,15.713728,78.241858,20.642183,58.561281,17.181690,NaN,20.283435,46.537941,20.743513,35.717997,896.092985
11761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Random Selection

In [4]:
#make a dictionary of robot current position and potential movement
pos_mov= {"Tree_Tr2":["Tree_Tr3","Tree_Tr5","Tree_Tr6"], 
          "Tree_Tr3":["Tree_Tr2","Tree_Tr5","Tree_Tr6"], 
          "Tree_Tr4":["Tree_Tr1","Tree_Tr5","Tree_Tr6"], 
          "Tree_Tr5":["Tree_Tr2","Tree_Tr3","Tree_Tr4","Tree_Tr1","Tree_Tr6"], 
          "Tree_Tr6":["Tree_Tr2","Tree_Tr3","Tree_Tr4","Tree_Tr1","Tree_Tr5"],
          "Tree_Tr1":["Tree_Tr4","Tree_Tr5","Tree_Tr6"]}

#get position
pos = list(pos_mov.keys())

In [5]:
#the number of observations selected per movement
desired_rows_data = 5

#check length of dataframe 
data_len = df.shape[0]

#get the number of movement for the robots
no_of_movement = data_len // desired_rows_data

#select only temperature columns. This signifies the different locations in the room
useful_cols2 = list(set(df.columns) - set(['54: TC_Smoke (°C)', '187: CO_room (ppm)']))

In [6]:
#create a new dataframe to store the randomly selected readings
new_dataset = collections.defaultdict(list)
pos_list=[]

#randomly select robot's initial position
init_pos = np.random.choice(["Tree_Tr2","Tree_Tr3"])
next_pos = init_pos.copy()
n_rows=0

#loop through all number of movements
for i in range(no_of_movement):     
    
    #collect data 
    for cols in useful_cols2:
        if cols.split("_", 1)[1].startswith(next_pos):
            col_name = cols.split("_")[-1]
            new_dataset[col_name].extend(list((df.loc[:,cols].values)[n_rows:n_rows+5]))
    n_rows+=5
    
    #append robot current position
    pos_list.append(next_pos)
    
    #select robot next position
    next_mov = np.random.choice(pos_mov[next_pos])
    next_pos = next_mov.copy()

In [7]:
custom_data = pd.DataFrame(new_dataset)
custom_data[['54: TC_Smoke (°C)', '187: CO_room (ppm)']] = df[['54: TC_Smoke (°C)', '187: CO_room (ppm)']]
custom_data

        060 (°C)   260 (°C)  54: TC_Smoke (°C)  187: CO_room (ppm)
0      10.114287  15.644292           8.613041          695.565623
1      10.116304  15.652686           8.614577          693.682888
2      10.113530  15.654990           8.612079          686.368593
3      10.104086  15.644093           8.603408          690.206866
4      10.104755  15.641486           8.608649          704.980179
...          ...        ...                ...                 ...
11755  15.947941  94.151162           7.451435          864.518459
11756  15.990016  95.106818           7.443393          860.245573
11757  16.002027  96.087471           7.438120          859.086899
11758  15.962836  97.108398           7.435278          873.570764
11759  15.935725  97.787657           7.450907          885.664478

[11760 rows x 4 columns]

# Data Labeling

In [8]:
#The dataset are labeled into three classes using CO and temperature readings at 60cm
#Because we assume the robot can only capture data at 60cm
#Pick temperature reading at 60cm
cols1 = list(custom_data.columns)
cols1[:1]

['060 (°C)']

In [9]:
#include class label into the dataframe
#create an empty dictionary 
df_labels= []

#iterate through the rows of the dataframe
#get the length of the dataframe
df_len = custom_data.shape[0]

for i in range(df_len):
    
    #if any of the values are greater than 600, set label == 2
    filter_rows =[num for num in list(custom_data.iloc[i][cols1[:1]]) if num > 600]   
    if len(filter_rows) > 0 or custom_data.iloc[i]["187: CO_room (ppm)"] > 1600:
        df_labels.append("danger")
        
    elif sum(list(custom_data.iloc[i][cols1[:1]].between(270, 600, inclusive='right'))) or \
        (custom_data.iloc[i]["187: CO_room (ppm)"] > 800 and custom_data.iloc[i]["187: CO_room (ppm)"] <= 1600):
        df_labels.append("caution")
        
    else:
        df_labels.append("safe")
        

#create another column in the original dataframe with the class labels
custom_data.loc[:,"labels"] = df_labels

#save to excel
custom_data.to_excel("Exp1_Labeled_Custom_data.xlsx", index=False)
custom_data

        060 (°C)   260 (°C)  54: TC_Smoke (°C)  187: CO_room (ppm)   labels
0      10.114287  15.644292           8.613041          695.565623     safe
1      10.116304  15.652686           8.614577          693.682888     safe
2      10.113530  15.654990           8.612079          686.368593     safe
3      10.104086  15.644093           8.603408          690.206866     safe
4      10.104755  15.641486           8.608649          704.980179     safe
...          ...        ...                ...                 ...      ...
11755  15.947941  94.151162           7.451435          864.518459  caution
11756  15.990016  95.106818           7.443393          860.245573  caution
11757  16.002027  96.087471           7.438120          859.086899  caution
11758  15.962836  97.108398           7.435278          873.570764  caution
11759  15.935725  97.787657           7.450907          885.664478  caution

[11760 rows x 5 columns]